version: "3.9"

services:
  chat-api:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - devopsgpt-network
    depends_on:
      - cache

  chat-ui:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://chat-api:3000
    networks:
      - devopsgpt-network
    depends_on:
      - chat-api

  cache:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - devopsgpt-network

networks:
  devopsgpt-network:
    driver: bridge
